name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: | echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image with Tags
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab
          echo "Building image: $IMAGE_NAME"

          docker build -t $IMAGE_NAME:latest .

          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          Image_Name=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab
          echo "Pushing image: $IMAGE_NAME"

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github,sha }}

      - name: Verify Images on Runner
        run: docker images
